# Generated by Django 3.2.2 on 2021-06-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerece', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
